/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    colors: {
      'system-neutron-star-text': '#f8fafc',
      'system-neutron-star-bg': '#475569',
      'system-red-star-text': '#fef2f2',
      'system-red-star-bg': '#b91c1c',
      'system-orange-star-text': '#431407',
      'system-orange-star-bg': '#fdba74',
      'system-blue-star-text': '#083344',
      'system-blue-star-bg': '#22d3ee',
      'system-young-star-text': '#022c22',
      'system-young-star-bg': '#6ee7b7',
      'system-white-dwarf-text': '#030712',
      'system-white-dwarf-bg': '#f9fafb',
      'system-black-hole-text': '#f9fafb',
      'system-black-hold-bg': '#030712',
      'system-hypergiant-text': '#2e1065',
      'system-hypergiant-bg': '#c4b5fd',
      'system-nebula-text': '#fdf2f8',
      'system-nebula-bg': '#db2777',
      'system-unstable-text': '#eef2ff',
      'system-unstable-bg': '#4f46e5',
      'waypoint-moon-text': '#f8fafc',
      'waypoint-moon-bg': '#64748b',
      'waypoint-gas-giant-text': '#fff7ed',
      'waypoint-gas-giant-bg': '#ea580c',
      'waypoint-nebula-text': '#422006',
      'waypoint-nebula-bg': '#fde047',
      'waypoint-asteroid-field-text': '#1a2e05',
      'waypoint-asteroid-field-bg': '#bef264',
      'waypoint-planet-text': '#ecfdf5',
      'waypoint-planet-bg': '#059669',
      'waypoint-debris-field-text': '#083344',
      'waypoint-debris-field-bg': '#67e8f9',
      'waypoint-orbital-station-text': '#fdf4ff',
      'waypoint-orbital-station-bg': '#c026d3',
      'waypoint-jump-gate-text': '#030712',
      'waypoint-jump-gate-bg': '#f9fafb',
      'waypoint-gravity-well-text': '#f9fafb',
      'waypoint-gravity-well-bg': '#030712',
    },
    extend: {},
  },
  plugins: [],
}
