-- Your SQL goes here
CREATE TABLE IF NOT EXISTS fleet (
  ship_symbol TEXT PRIMARY KEY NOT NULL,
  reg_name TEXT NOT NULL,
  reg_faction_symbol TEXT NOT NULL,
  reg_role TEXT NOT NULL,
  nav_system_symbol TEXT NOT NULL,
  nav_status TEXT NOT NULL,
  nav_flight_mode TEXT NOT NULL,
  nav_waypoint_symbol TEXT NOT NULL,
  nav_route_dest_symbol TEXT NOT NULL,
  nav_route_dest_waypoint_type TEXT NOT NULL,
  nav_route_dest_system_symbol TEXT NOT NULL,
  nav_route_dest_x INT NOT NULL,
  nav_route_dest_y INT NOT NULL,
  nav_route_dep_symbol TEXT NOT NULL,
  nav_route_dep_waypoint_type TEXT NOT NULL,
  nav_route_dep_system_symbol TEXT NOT NULL,
  nav_route_dep_x INT NOT NULL,
  nav_route_dep_y INT NOT NULL,
  nav_route_departure_time TEXT NOT NULL,
  nav_route_dest_arrival_time TEXT NOT NULL,
  crew_current INT NOT NULL,
  crew_required INT NOT NULL,
  crew_capacity INT NOT NULL,
  crew_rotation TEXT NOT NULL,
  crew_moral INT NOT NULL,
  crew_wages INT NOT NULL,
  frame_symbol TEXT NOT NULL,
  frame_name TEXT NOT NULL,
  frame_desc TEXT NOT NULL,
  frame_condition REAL NOT NULL,
  frame_modules INT NOT NULL,
  frame_mounts INT NOT NULL,
  frame_fuel_capacity INT NOT NULL,
  frame_req_power INT,
  frame_req_crew INT,
  frame_req_slots INT,
  reactor_symbol TEXT NOT NULL,
  reactor_name TEXT NOT NULL,
  reactor_desc TEXT NOT NULL,
  reactor_condition INT NOT NULL,
  reactor_power_output INT NOT NULL,
  reactor_req_power INT,
  reactor_req_crew INT,
  reactor_req_slots INT,
  engine_symbol TEXT NOT NULL,
  engine_name TEXT NOT NULL,
  engine_desc TEXT NOT NULL,
  engine_condition INT NOT NULL,
  engine_speed INT NOT NULL,
  engine_req_power INT,
  engine_req_crew INT,
  engine_req_slots INT,
  modules TEXT NOT NULL,
  mounts TEXT NOT NULL,
  cargo TEXT NOT NULL,
  fuel_current INT NOT NULL,
  fuel_capacity INT NOT NULL,
  fuel_consumed_amount INT NOT NULL,
  fuel_consumed_timestamp TEXT NOT NULL
)