-- Your SQL goes here
CREATE TABLE IF NOT EXISTS fleet (
  ship_symbol TEXT PRIMARY KEY NOT NULL,
  reg_name TEXT NOT NULL,
  reg_faction_symbol TEXT NOT NULL,
  reg_role TEXT NOT NULL,
  nav_system_symbol TEXT NOT NULL,
  nav_status TEXT NOT NULL,
  nav_flight_mode TEXT NOT NULL,
  nav_waypoint_symbol TEXT NOT NULL,
  nav_departure_time TEXT NOT NULL,
  nav_arrival_time TEXT NOT NULL,
  nav_dest_symbol TEXT NOT NULL,
  nav_dest_waypoint_type TEXT NOT NULL,
  nav_dest_system_symbol TEXT NOT NULL,
  nav_dest_x INTEGER NOT NULL,
  nav_dest_y INTEGER NOT NULL,
  nav_dep_symbol TEXT NOT NULL,
  nav_dep_waypoint_type TEXT NOT NULL,
  nav_dep_system_symbol TEXT NOT NULL,
  nav_dep_x INTEGER NOT NULL,
  nav_dep_y INTEGER NOT NULL,
  crew_current INTEGER NOT NULL,
  crew_required INTEGER NOT NULL,
  crew_capacity INTEGER NOT NULL,
  crew_rotation TEXT NOT NULL,
  crew_moral REAL NOT NULL,
  crew_wages INTEGER NOT NULL,
  frame_symbol TEXT NOT NULL,
  frame_name TEXT NOT NULL,
  frame_desc TEXT NOT NULL,
  frame_condition REAL NOT NULL,
  frame_modules INTEGER NOT NULL,
  frame_mounts INTEGER NOT NULL,
  frame_fuel_capacity INTEGER NOT NULL,
  frame_req_power INTEGER,
  frame_req_crew INTEGER,
  frame_req_slots INTEGER,
  reactor_symbol TEXT NOT NULL,
  reactor_name TEXT NOT NULL,
  reactor_desc TEXT NOT NULL,
  reactor_condition REAL NOT NULL,
  reactor_power_output INTEGER NOT NULL,
  reactor_req_power INTEGER,
  reactor_req_crew INTEGER,
  reactor_req_slots INTEGER,
  engine_symbol TEXT NOT NULL,
  engine_name TEXT NOT NULL,
  engine_desc TEXT NOT NULL,
  engine_condition REAL NOT NULL,
  engine_speed INTEGER NOT NULL,
  engine_req_power INTEGER,
  engine_req_crew INTEGER,
  engine_req_slots INTEGER,
  cargo_capacity INTEGER NOT NULL,
  cargo_units INTEGER NOT NULL,
  fuel_current INTEGER NOT NULL,
  fuel_capacity INTEGER NOT NULL,
  fuel_consumed_amount INTEGER NOT NULL,
  fuel_consumed_timestamp TEXT NOT NULL
)